use super::*;

#[derive(Debug, Serialize)]
pub struct MetricsParams {
    pub operation_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub manifest_root_digest: Option<String>,
    pub total_duration: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub archive_duration: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub upload_duration: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub download_duration: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extract_duration: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub confirm_duration: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uncompressed_size: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compressed_size: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compression_ratio: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_count: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub upload_speed_mbps: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub download_speed_mbps: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_age_hours: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub benchmark_compression_ratio: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compression_duration: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub predicted_time_ms: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prediction_accuracy: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compression_algorithm: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_cores: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cpu_load_percent: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_memory_gb: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub available_memory_gb: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub memory_strategy: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disk_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disk_speed_estimate_mb_s: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub concurrent_operations: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub buffer_size_mb: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_size_mb: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub concurrency_level: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub streaming_enabled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compression_level: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compression_threads: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub benchmark_throughput_mb_s: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bandwidth_probe_mb_s: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub multipart_threshold_mb: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_count: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retry_count: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transfer_size: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_efficiency: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub storage_region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub storage_cache_status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub storage_block_location: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub storage_timing: Option<String>,
}
